# Generated by Django 4.0.2 on 2023-02-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobScraped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=5000, null=True)),
                ('company', models.CharField(blank=True, max_length=5000, null=True)),
                ('announcement', models.CharField(blank=True, max_length=5000, null=True)),
                ('description', models.CharField(blank=True, max_length=500000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
