# Generated by Django 4.0.2 on 2023-03-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=2500)),
                ('companyname', models.CharField(db_column='companyName', max_length=2500)),
                ('location', models.CharField(blank=True, max_length=2500, null=True)),
                ('via', models.CharField(blank=True, max_length=2500, null=True)),
                ('description', models.CharField(blank=True, max_length=2500, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=2500, null=True)),
                ('applylink', models.CharField(db_column='applyLink', max_length=2500, unique=True)),
                ('postedat', models.CharField(blank=True, db_column='postedAt', max_length=2500, null=True)),
                ('scheduletype', models.CharField(blank=True, db_column='scheduleType', max_length=2500, null=True)),
                ('applylinktitle', models.CharField(blank=True, db_column='applyLinkTitle', max_length=2500, null=True)),
                ('salary', models.CharField(blank=True, max_length=2500, null=True)),
                ('workfromhome', models.BooleanField(db_column='workFromHome')),
                ('responsibilities', models.TextField()),
                ('qualifications', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'job',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Qualifications',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=2500)),
            ],
            options={
                'db_table': 'qualifications',
                'managed': False,
            },
        ),
    ]
