# Generated by Django 4.0.2 on 2023-03-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_job_qualifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=40000, null=True)),
                ('file_name', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
